name: CC4S Research group
url: http://awesome.example.edu

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html


projects:
  eom: {url: '/research/eom/', title: 'Excited states'}
  h2oathbn: {url: '/research/h2oathbn/', title: '$H_2O$ on $BN$'}
  lowrank: {url: '/research/lowrank/', title: 'Low Rank factorization'}

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: People
      link: /people.html
    - title: Research
      link: /research/
    - title: Teaching
      link: /teaching/
    - title: Publications
      link: /publications.html
    - title: Code
      link: /code.html
